name:cicd pipeline

on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: checkout code
      user: actions/checkout@v5

    - name: set up Node.js  
      user: actions/checkout@v3
      with: 
            node-version: 16
    - name: install dependencies
      run: npm install 

    - name: Run tests
      run: npm test 
